jorurimail_db:
   image: ftakao2007/jorurimail_db:latest
   container_name: jorurimail_db
   tty: true
   expose:
     - "3306"
   command: sh -c 'service mysqld restart && /bin/bash --login'

jorurimail_web:
   image: ftakao2007/jorurimail_web:latest
   container_name: jorurimail_web
   tty: true
   links:
     - jorurimail_db
   ports:
     - "8082:80"
   command: sh -c '/root/init_jorurimail_web.sh'
   #command: sh -c ' service httpd start && /bin/bash --login'
