jorurigw_db_centos7:
   image: ftakao2007/jorurigw_db_centos7:latest
   container_name: jorurigw_db_centos7
   tty: true
   privileged: true
   expose:
     - "3306"
   command: /sbin/init && /root/jorurigw_db_centos7.sh

jorurigw_web_centos7:
   image: ftakao2007/jorurigw_web_centos7:latest
   container_name: jorurigw_web_centos7
   tty: true
   privileged: true
   links:
     - jorurigw_db_centos7
   ports:
     - "8094:80"
   command: /sbin/init && /root/init_jorurigw_web_centos7.sh
   #command: /sbin/init && /usr/local/apache/bin/apachectl start
