- hosts: docker_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: deploy centos container
      docker: 
        image=centos:centos6
        name=ldap
        expose=389
        ports=389:389
        tty=yes
