---
- hosts: jorurimail_web_centos7
  become: yes
  connection: docker
  gather_facts: no
  vars:
    web_server_ip: XXX.XXX.XXX.XXX
    user: joruri
    group: joruri
    user_uid: 1001
    user_passwd: $1$SomeSalt$ZSU2MwC9RbVz5E6EYFgjV1
    ruby_version: 2.3.1
    ruby_library_version: "2.3.0"
    #passenger_version: "5.0.30"
    passenger_version: "5.0.29"
  roles:

    # rbenvのインストール
    - {role: ../common-roles/rbenv.centos7,
       rbenv_ruby_version: "{{ ruby_version }}",
       tags: rbenv
      }

    # httpdのインストール
    - {role: ../common-roles/httpd2.4.centos7,
       httpd_server_ip: "{{ web_server_ip }}",
       apache_user: "{{ user }}",
       apache_group: "{{ group }}",
       httpd_logrotate_template: httpd.logrotate.j2,
       httpd_conf_template: httpd.conf.j2,
       tags: httpd
      }

    # passenger5のインストール
    - {role: ../common-roles/passenger5.rbenv.centos7,
       passenger_conf_template: passenger.conf.rbenv.tj2,
       ruby_version: 2.3.1,
       tags: passenger
      }
   
    # JoruriMailの設定
    - {role: ../common-roles/jorurimail.centos7, 
       tags: jorurimail
      }
