- hosts: docker_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: deploy centos container
      docker: 
        image=centos:centos6
        name=jorurigw_web
        ports=8084:80
        expose=80
        tty=yes
