---
- hosts: deco_db
  become: yes
  connection: docker
  gather_facts: no
  vars:
    db_user: deco
    db_user_password: 'pass'
    db_user_root_password: 'pass'
  roles:

    # mysql5.6.centosのインストール
    - {role: ../common-roles/mysql5.6.centos,
       my_conf_template: my.cnf.j2,
       my_conf_server_id: 54321,
       mysql_root_password: '{{ db_user_root_password }}',
       mysql_operation_user: '{{ db_user }}',
       mysql_operation_user_password: '{{ db_user_password }}',
       create_database: 'production_jorurigw',
       tags: mysql
      }
