rocketchat:
  image: rocketchat/rocket.chat
  environment:
    - MONGO_URL=mongodb://mongodb/rocketchat
    - ROOT_URL=http://localhost:80
  links:
    - mongodb
  ports:
    - 8091:80

mongodb:
   image: mongo
   volumes:
     - ~/containers/rocketchat:/data/db
   ports:
     - 27017
