- hosts: docker_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: deploy centos container
      docker: 
        image: centos:centos7
        name: operation_centos7
        ports:
          - "2222:22"
        privileged: yes
        tty: yes
        command: /sbin/init
