---
- hosts: all
  gather_facts: yes
  become: yes
  connection: docker
  vars:
    user_name: vagrant
  roles:

    # pipのインストール
    - {role: ../common-roles/pip.centos,
       tags: pip
      }

    # ansibleのインストール
    - {role: ../common-roles/ansible.centos,
       tags: ansible
      }

    # rbenvのインストール
    - {role: ../common-roles/ftakao2007.rbenv.centos, rbenv_ruby_version: 2.3.1,
       tags: rbenv
      }

  post_tasks:
    - name: ftakao2007/workをcloneする
      git: dest=/home/{{ user_name }}/work repo=https://github.com/ftakao2007/work.git
