jorurigw_db_centos7:
   image: ftakao2007/jorurigw_db_centos7:latest
   container_name: jorurigw_db_centos7
   tty: true
   privileged: true
   expose:
     - "3306"
   command: /sbin/init && systemctl start mysqld.service
   #command: /sbin/init && sh -c '/root/jorurigw_db_centos7.sh'

ldap:
   image: ftakao2007/ldap:latest
   container_name: ldap
   tty: true
   ports:
     - "389:389"
   expose:
     - "389"
   command: sh -c 'service slapd restart && service rsyslog restart && /bin/bash --login'

smtp_ldap:
   image: ftakao2007/smtp_ldap:latest
   container_name: smtp_ldap
   tty: true
   privileged: true
   volumes:
     - /home
   links:
     - ldap
   expose:
     - "25"
     - "587"
   command: sh -c '/bin/sh /root/init_smtp_ldap.sh'
   #command: sh -c 'service postfix restart && service rsyslog restart && /bin/bash --login'

jorurigw_web_centos7:
   image: ftakao2007/jorurigw_web_centos7:latest
   container_name: jorurigw_web_centos7
   tty: true
   privileged: true
   links:
     - smtp_ldap
     - ldap
     - jorurigw_db_centos7
   ports:
     - "8084:80"
   command: /sbin/init && sh -c '/root/init_jorurigw_web_ldap_smtp_centos7.sh'
   #command: /sbin/init && sh -c '/root/init_jorurigw_web_ldap_smtp.sh'
   #command: /sbin/init && systemctl httpd.service start
