- hosts: docker_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: deploy centos container
      docker: 
        image=centos:centos6
        name=jorurimail_db
        expose=3306
        tty=yes

    - name: deploy centos container
      docker: 
        image=centos:centos6
        name=jorurimail_web
        links=jorurimail_db:jorurimail_db
        ports=8082:80
        expose=80
        tty=yes

