---
- hosts: jorurimail_webdb
  become: yes
  connection: docker
  gather_facts: no
  vars:
    web_server_ip: XXX.XXX.XXX.XXX
    user: joruri
    group: joruri
    user_uid: 1001
    user_passwd: $1$SomeSalt$ZSU2MwC9RbVz5E6EYFgjV1
    db_user: joruri
    db_user_password: 'pass'
    db_user_root_password: 'pass'
    ruby_library_version: "1.9.1"
    passenger_version: "3.0.9"
    rails_version: "3.0.0"
  roles:

    # mysql5.6.centosのインストール
    - {role: ../common-roles/mysql5.6.centos,
       my_conf_template: my.cnf.j2,
       my_conf_server_id: 123456,
       mysql_root_password: '{{ db_user_root_password }}',
       mysql_operation_user: '{{ db_user }}',
       mysql_operation_user_password: '{{ db_user_password }}',
       create_database: 'jorurimail',
       tags: mysql
      }

    # ruby-1.9.2-p290のインストール
    - {role: ../common-roles/ruby-1.9.2-p290.centos,
       tags: ruby
      }

    # railsのインストール
    - {role: ../common-roles/rails.centos,
       tags: rails
      }

    # httpdのインストール
    - {role: ../common-roles/httpd2.2.centos,
       httpd_server_ip: "{{ web_server_ip }}",
       httpd_conf_template: httpd.conf.j2,
       httpd_logrotate_template: httpd.logrotate.j2,
       tags: httpd
      }

    # passenger3.0.9のインストール
    - {role: ../common-roles/passenger3.0.9.ruby.centos,
       passenger_conf_template: passenger.conf.ruby.tj2,
       tags: passenger
      }
   
    # JoruriMailの設定
    - {role: ../common-roles/jorurimail.centos, 
       tags: jorurimail
      }
