jorurigw_db_centos7:
   image: ftakao2007/jorurigw_db_centos7:latest
   container_name: jorurigw_db_centos7
   tty: true
   privileged: true
   expose:
     - "3306"
   command: /sbin/init && systemctl start mysqld.service
   #command: /sbin/init && sh -c '/root/jorurigw_db_centos7.sh'

jorurigw_web_centos7:
   image: ftakao2007/jorurigw_web_centos7:latest
   container_name: jorurigw_web_centos7
   tty: true
   privileged: true
   links:
     - jorurigw_db_centos7
   ports:
     - "8095:80"
   command: /sbin/init && sh -c '/root/init_jorurigw_web_ldap_smtp.sh'
   #command: /sbin/init && systemctl httpd.service start
