ldap:
   image: ftakao2007/ldap
   container_name: ldap
   privileged: true
   tty: true
   expose:
     - 389
   command: sh -c 'service slapd restart && service rsyslog restart && /bin/bash --login'

base_ldap:
   image: base_ldap:latest
   container_name: base_ldap
   privileged: true
   tty: true
   ports:
     - "2222:22"
   links:
     - ldap
     #- ldap_pref
   command: sh -c 'service sshd restart && service rsyslog restart && /bin/bash --login'

