operation_centos7_gui:
   image: ftakao2007/operation_centos7:gui
   container_name: operation_centos7_gui
   privileged: true
   tty: true
   ports:
     - "2222:22"
     - "3000:3000"
     - "3389:3389"
     - "5901:5901"
   command: /sbin/init && systemctl restart sshd && systemctl restart xrdp.service 

   ### How to use VNC
   # [ftakao2007@vncserver]
   # $ sudo systemctl restart vncserver@:2.service
   # [VNC client]
   # vnc://(docker host):5901
   # ftakao2007/vagrant
