base:
   image: ftakao2007/base:latest
   container_name: base
   privileged: true
   tty: true
   ports:
     - "2222:22"
   command: sh -c 'service sshd restart && service rsyslog restart && /bin/bash --login'

